In [ ]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import re

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
path = "drive/My Drive/tweets(1).csv"
df = pd.read_csv(path, encoding='ISO-8859-1')
df.head()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


text  label
0  It's like I have two brains fighting against o...      1
1  there is sadness deep inside my guts It sits n...      1
2  i thought i was getting better? like i started...      1
3  is it strange when a part of you wishes to get...      1
4  I cut myself Nothing happens I overdose Nothin...      1

In [ ]:
# pd.set_option('display.max_colwidth', -1)
# df.head(10)

In [ ]:
df.describe()

label
count  6200.000000
mean      0.190484
std       0.392714
min       0.000000
25%       0.000000
50%       0.000000
75%       0.000000
max       1.000000

In [ ]:
df.count()

text     6200
label    6200
dtype: int64

Dropping duplicates and NaN from the dataframe

In [ ]:
df = df.dropna()
df = df.drop_duplicates()

In [ ]:
df.count()

text     6139
label    6139
dtype: int64

In [ ]:
import re
import string
import numpy as np
import nltk
stopwords = nltk.download('stopwords')
from nltk.stem import PorterStemmer
from nltk.tokenize import TweetTokenizer



def remove_contractions(tweet):
    tweet = str(tweet)
    # Contractions
    tweet = re.sub(r"\x89Ûª", "'", tweet)
    tweet = re.sub(r"he's", "he is", tweet)
    tweet = re.sub(r"there's", "there is", tweet)
    tweet = re.sub(r"We're", "We are", tweet)
    tweet = re.sub(r"That's", "That is", tweet)
    tweet = re.sub(r"won't", "will not", tweet)
    tweet = re.sub(r"they're", "they are", tweet)
    tweet = re.sub(r"Can't", "Cannot", tweet)
    tweet = re.sub(r"wasn't", "was not", tweet)
    tweet = re.sub(r"don\x89Ûªt", "do not", tweet)
    tweet = re.sub(r"aren't", "are not", tweet)
    tweet = re.sub(r"isn't", "is not", tweet)
    tweet = re.sub(r"What's", "What is", tweet)
    tweet = re.sub(r"haven't", "have not", tweet)
    tweet = re.sub(r"hasn't", "has not", tweet)
    tweet = re.sub(r"There's", "There is", tweet)
    tweet = re.sub(r"He's", "He is", tweet)
    tweet = re.sub(r"It's", "It is", tweet)
    tweet = re.sub(r"You're", "You are", tweet)
    tweet = re.sub(r"I'M", "I am", tweet)
    tweet = re.sub(r"shouldn't", "should not", tweet)
    tweet = re.sub(r"wouldn't", "would not", tweet)
    tweet = re.sub(r"i'm", "I am", tweet)
    tweet = re.sub(r"I\x89Ûªm", "I am", tweet)
    tweet = re.sub(r"I'm", "I am", tweet)
    tweet = re.sub(r"Isn't", "is not", tweet)
    tweet = re.sub(r"Here's", "Here is", tweet)
    tweet = re.sub(r"you've", "you have", tweet)
    tweet = re.sub(r"you\x89Ûªve", "you have", tweet)
    tweet = re.sub(r"we're", "we are", tweet)
    tweet = re.sub(r"what's", "what is", tweet)
    tweet = re.sub(r"couldn't", "could not", tweet)
    tweet = re.sub(r"we've", "we have", tweet)
    tweet = re.sub(r"it\x89Ûªs", "it is", tweet)
    tweet = re.sub(r"doesn\x89Ûªt", "does not", tweet)
    tweet = re.sub(r"It\x89Ûªs", "It is", tweet)
    tweet = re.sub(r"Here\x89Ûªs", "Here is", tweet)
    tweet = re.sub(r"who's", "who is", tweet)
    tweet = re.sub(r"I\x89Ûªve", "I have", tweet)
    tweet = re.sub(r"y'all", "you all", tweet)
    tweet = re.sub(r"can\x89Ûªt", "cannot", tweet)
    tweet = re.sub(r"would've", "would have", tweet)
    tweet = re.sub(r"it'll", "it will", tweet)
    tweet = re.sub(r"we'll", "we will", tweet)
    tweet = re.sub(r"wouldn\x89Ûªt", "would not", tweet)
    tweet = re.sub(r"We've", "We have", tweet)
    tweet = re.sub(r"he'll", "he will", tweet)
    tweet = re.sub(r"Y'all", "You all", tweet)
    tweet = re.sub(r"Weren't", "Were not", tweet)
    tweet = re.sub(r"Didn't", "Did not", tweet)
    tweet = re.sub(r"they'll", "they will", tweet)
    tweet = re.sub(r"they'd", "they would", tweet)
    tweet = re.sub(r"DON'T", "DO NOT", tweet)
    tweet = re.sub(r"That\x89Ûªs", "That is", tweet)
    tweet = re.sub(r"they've", "they have", tweet)
    tweet = re.sub(r"i'd", "I would", tweet)
    tweet = re.sub(r"should've", "should have", tweet)
    tweet = re.sub(r"You\x89Ûªre", "You are", tweet)
    tweet = re.sub(r"where's", "where is", tweet)
    tweet = re.sub(r"Don\x89Ûªt", "Do not", tweet)
    tweet = re.sub(r"we'd", "we would", tweet)
    tweet = re.sub(r"i'll", "I will", tweet)
    tweet = re.sub(r"weren't", "were not", tweet)
    tweet = re.sub(r"They're", "They are", tweet)
    tweet = re.sub(r"Can\x89Ûªt", "Cannot", tweet)
    tweet = re.sub(r"you\x89Ûªll", "you will", tweet)
    tweet = re.sub(r"I\x89Ûªd", "I would", tweet)
    tweet = re.sub(r"let's", "let us", tweet)
    tweet = re.sub(r"it's", "it is", tweet)
    tweet = re.sub(r"can't", "cannot", tweet)
    tweet = re.sub(r"don't", "do not", tweet)
    tweet = re.sub(r"you're", "you are", tweet)
    tweet = re.sub(r"i've", "I have", tweet)
    tweet = re.sub(r"that's", "that is", tweet)
    tweet = re.sub(r"i'll", "I will", tweet)
    tweet = re.sub(r"doesn't", "does not", tweet)
    tweet = re.sub(r"i'd", "I would", tweet)
    tweet = re.sub(r"didn't", "did not", tweet)
    tweet = re.sub(r"ain't", "am not", tweet)
    tweet = re.sub(r"you'll", "you will", tweet)
    tweet = re.sub(r"I've", "I have", tweet)
    tweet = re.sub(r"Don't", "do not", tweet)
    tweet = re.sub(r"I'll", "I will", tweet)
    tweet = re.sub(r"I'd", "I would", tweet)
    tweet = re.sub(r"Let's", "Let us", tweet)
    tweet = re.sub(r"you'd", "You would", tweet)
    tweet = re.sub(r"It's", "It is", tweet)
    tweet = re.sub(r"Ain't", "am not", tweet)
    tweet = re.sub(r"Haven't", "Have not", tweet)
    tweet = re.sub(r"Could've", "Could have", tweet)
    tweet = re.sub(r"youve", "you have", tweet)  
    tweet = re.sub(r"donå«t", "do not", tweet)   
            
    # Character entity references
    tweet = re.sub(r"&amp;", "&", tweet)
    return tweet


def process_tweet(tweet):
    """Process tweet function.
    Input:
        tweet: a string containing a tweet
    Output:
        tweets_clean: a list of words containing the processed tweet
    """
    tweet = str(tweet)
    stemmer = PorterStemmer()
    # stopwords_english = nltk.download('stopwords').words('english')
    stopwords_english = set(nltk.corpus.stopwords.words('english'))

    # remove stock market tickers like $GE
    tweet = re.sub(r'\$\w*', '', tweet)

    # remove old style retweet text "RT"
    tweet = re.sub(r'^RT[\s]+', '', tweet)

    # remove hyperlinks
    tweet = re.sub(r'https?:\/\/.*[\r\n]*', '', tweet)

    # remove hashtags
    # only removing the hash # sign from the word
    tweet = re.sub(r'#', '', tweet)

    # tokenize tweets
    tokenizer = TweetTokenizer(preserve_case=False, strip_handles=True, reduce_len=True)
    tweet_tokens = tokenizer.tokenize(tweet)

    #remove contractions
    tweet = remove_contractions(tweet)
    
    tweets_clean = []
    for word in tweet_tokens:
        if (word not in stopwords_english and word not in string.punctuation):
            stem_word = stemmer.stem(word)
            tweets_clean.append(stem_word)
    
    clean_tweet = ' '.join(map(str, tweets_clean))
    return clean_tweet

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [ ]:
df.tail(10)


text  label
6190                                I am so happy today      0
6191                        That was the best game ever      0
6192                                    This is so good      0
6193                        What a beautiful day today!      0
6194                    I made the best cake ever today      0
6195         Check out this post. This is so awesome!!!      0
6196               OMG! Look at her dress. So beautiful      0
6197               Sunsets are the best time of the day      0
6198  I have got the bestest friends! Checkout what ...      0
6199                              Beach walks are love!      0

In [ ]:
df['text'] = df['text'].str.lower().str.replace('[^\w\s]',' ').str.replace('\s\s+', ' ')
df.head(10)

text  label
0  it s like i have two brains fighting against o...      1
1  there is sadness deep inside my guts it sits n...      1
2  i thought i was getting better like i started ...      1
3  is it strange when a part of you wishes to get...      1
4  i cut myself nothing happens i overdose nothin...      1
5  why can t i escape my thoughts of suicide and ...      1
6  sleep doesn t give me the relief i need from m...      1
7  why do i even fucking bother anymore my existe...      1
8  terrible things keep happening and like i don ...      1
9  bout to depression buy these onlyfans while i ...      0

In [ ]:
df['text'] = df['text'].apply(lambda tweet: process_tweet(tweet))

In [ ]:
df.head(10)

text  label
0  like two brain fight one anoth one want die hu...      1
1  sad deep insid gut sit next anxieti taunt day ...      1
2  thought get better like start take care work m...      1
3               strang part wish get corona hope die      1
4  cut noth happen overdos noth happen life bulls...      1
5  escap thought suicid self harm feel good bette...      1
6                      sleep give relief need suffer      1
7               even fuck bother anymor exist mistak      1
8   terribl thing keep happen like capac deal anymor      1
9                 bout depress buy onlyfan quarantin      0

Tweet has been cleaned to normal text.

In [ ]:
df.head(10)

text  label
0  like two brain fight one anoth one want die hu...      1
1  sad deep insid gut sit next anxieti taunt day ...      1
2  thought get better like start take care work m...      1
3               strang part wish get corona hope die      1
4  cut noth happen overdos noth happen life bulls...      1
5  escap thought suicid self harm feel good bette...      1
6                      sleep give relief need suffer      1
7               even fuck bother anymor exist mistak      1
8   terribl thing keep happen like capac deal anymor      1
9                 bout depress buy onlyfan quarantin      0

**Sampling to balance out the no. of 1s and 0s**

In [ ]:
from sklearn.utils import resample
df_majority = df[df.label==0]
df_minority = df[df.label==1]
 
# Upsample minority class
df_minority_upsampled = resample(df_minority, 
                                 replace=True,     # sample with replacement
                                 n_samples=len(df_majority),    # to match majority class
                                 random_state=123) # reproducible results
 
# Combine majority class with upsampled minority class
df_upsampled = pd.concat([df_majority, df_minority_upsampled])
 
# Display new class counts
print("Before")
print(df.label.value_counts())
print("After")
print(df_upsampled.label.value_counts())

Before
0    4960
1    1179
Name: label, dtype: int64
After
1    4960
0    4960
Name: label, dtype: int64


### **LSTM**

In [ ]:
import tensorflow as tf
tf.version.VERSION

'2.4.1'

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [ ]:
tweet=df_upsampled.text.values
tokenizer=Tokenizer(num_words=10000)
tokenizer.fit_on_texts(tweet)

In [ ]:
vocab_size=len(tokenizer.word_index)+1
encoded_docs=tokenizer.texts_to_sequences(tweet)
padded_sequence = pad_sequences(encoded_docs)

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM,Dense, Dropout
from tensorflow.keras.layers import SpatialDropout1D
from tensorflow.keras.layers import Embedding
from tensorflow.keras.metrics import Recall, FalseNegatives, Precision
from keras import Sequential

In [ ]:
embedding_vector_length = 32
model = Sequential()
model.add(Embedding(vocab_size, embedding_vector_length,     
                                     input_length=200) )
model.add(SpatialDropout1D(0.25))
model.add(LSTM(50, dropout=0.5, recurrent_dropout=0.5))
model.add(Dropout(0.2))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam', 
                           metrics=['accuracy', Recall(), FalseNegatives(), Precision()])
print(model.summary())

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 200, 32)           415296    
_________________________________________________________________
spatial_dropout1d (SpatialDr (None, 200, 32)           0         
_________________________________________________________________
lstm (LSTM)                  (None, 50)                16600     
_________________________________________________________________
dropout (Dropout)            (None, 50)                0         
_________________________________________________________________
dense (Dense)                (None, 1)                 51        
Total params: 431,947
Trainable params: 431,947
Non-trainable params: 0
_________________________________________________________________
None


In [ ]:
sentiment_label=df_upsampled['label'].to_numpy()
sentiment_label

array([0, 0, 0, ..., 1, 1, 1])

In [ ]:
print(len(padded_sequence))
print(len(sentiment_label))

9920
9920


In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(padded_sequence, sentiment_label, test_size = 0.2, random_state = 0)
X_test = np.array(X_test)
y_test = np.array(y_test)
print(X_test)
print()
print(y_test)

[[   0    0    0 ...  356 1218 1232]
 [   0    0    0 ...  470  122 1691]
 [   0    0    0 ...  326  659 1901]
 ...
 [   0    0    0 ...   42  621  786]
 [   0    0    0 ... 1873   27  576]
 [   0    0    0 ... 8620 8621  270]]

[0 1 0 ... 0 1 0]


In [ ]:
history = model.fit(padded_sequence,
                    sentiment_label,
                    validation_split=0.2, 
                    epochs=5, 
                    batch_size=64)

Epoch 1/5
124/124 [==============================] - 11s 68ms/step - loss: 0.6569 - accuracy: 0.6090 - recall: 0.1016 - false_negatives: 1363.2720 - precision: 0.4537 - val_loss: 0.8837 - val_accuracy: 0.3972 - val_recall: 0.3972 - val_false_negatives: 1196.0000 - val_precision: 1.0000
Epoch 2/5
124/124 [==============================] - 7s 59ms/step - loss: 0.4854 - accuracy: 0.7641 - recall: 0.5858 - false_negatives: 557.0720 - precision: 0.7236 - val_loss: 0.6553 - val_accuracy: 0.7475 - val_recall: 0.7475 - val_false_negatives: 501.0000 - val_precision: 1.0000
Epoch 3/5
124/124 [==============================] - 7s 59ms/step - loss: 0.3435 - accuracy: 0.8415 - recall: 0.8173 - false_negatives: 272.7520 - precision: 0.7749 - val_loss: 0.5703 - val_accuracy: 0.7792 - val_recall: 0.7792 - val_false_negatives: 438.0000 - val_precision: 1.0000
Epoch 4/5
124/124 [==============================] - 7s 59ms/step - loss: 0.2667 - accuracy: 0.8873 - recall: 0.8645 - false_negatives: 207.0000 

In [ ]:
results = model.evaluate(X_test, y_test)
for name,value in zip(model.metrics_names, results):
  print(f'{name}: {value}')

62/62 [==============================] - 1s 8ms/step - loss: 0.2512 - accuracy: 0.9189 - recall: 0.9041 - false_negatives: 98.0000 - precision: 0.9362
loss: 0.251228928565979
accuracy: 0.9188507795333862
recall: 0.9041095972061157
false_negatives: 98.0
precision: 0.936170220375061


In [ ]:
#sample_data = pd.read_excel("BE_Project.xlsx")
#testdata=sample_data.iloc[:50,0].values
testdata="I am so happy"
testdata = process_tweet(testdata)
#print(testdata)
#for data in testdata:
#test_word = data
tw = tokenizer.texts_to_sequences([testdata]) #test_word
tw = pad_sequences(tw,maxlen=200)
prediction = int(model.predict(tw).round().item())
if prediction==1: print(testdata+"\t\t"+ str(prediction)+":"+"Suicidal")
else: print(testdata+"\t\t"+ str(prediction)+":"+"Not Suicidal")

happi		1:Suicidal


In [ ]:
def predict(tweet):
  clean_tweet = process_tweet(tweet)
  tw = tokenizer.texts_to_sequences([clean_tweet]) #test_word
  tw = pad_sequences(tw,maxlen=200)
  prediction = int(model.predict(tw).round().item())
  res = model.predict(tw)
  print(res)
  if prediction==1: print(clean_tweet+"\t\t"+ str(prediction)+":"+"Suicidal")
  else: print(clean_tweet+"\t\t"+ str(prediction)+":"+"Not Suicidal")

In [ ]:
predict("I am so happy")

[[0.5072896]]
happi		1:Suicidal


In [ ]:
predict("I miss you mumma")

[[0.6217644]]
miss mumma		1:Suicidal


In [ ]:
predict("what point is there in living anymore?")

[[0.8758241]]
point live anymor		1:Suicidal


In [ ]:
# serialize model to JSON
model_json = model.to_json()
with open("model_r.json", "w") as json_file:
    json_file.write(model_json)
# serialize weights to HDF5
model.save_weights("model_r.h5")
print("Saved model to disk")
 
# later...


Saved model to disk


In [ ]:
# from keras.models import model_from_json
# # load json and create model
# json_file = open('model_t.json', 'r')
# loaded_model_json = json_file.read()
# json_file.close()
# loaded_model = model_from_json(loaded_model_json)
# # load weights into new model
# loaded_model.load_weights("model_t.h5")
# print("Loaded model from disk")

# loaded_model.predict(np.array(["I am so fucking depressed"]))

In [ ]:
#model.save('model_t.h5')

In [ ]:
import pickle
with open('tokenizer_r.pickle', 'wb') as handle:
    pickle.dump(tokenizer, handle, protocol=pickle.HIGHEST_PROTOCOL)

In [ ]:
# loaded_model = tf.keras.models.load_model('model_t.h5')
# with open('tokenizer.pickle', 'rb') as handle:
#     loaded_tokenizer = pickle.load(handle)

In [ ]:
# txt="Check out this post on the number of people who suicided this year"
# seq= loaded_tokenizer.texts_to_sequences([txt])
# padded = pad_sequences(seq, maxlen=200)
# pred = model.predict_classes(padded)
# print(pred)